In [1]:
#First ==> How To Make Session
import tensorflow as tf      
tf.compat.v1.disable_eager_execution()
#sess= tf.Session()
sess=tf.compat.v1.keras.backend.get_session()
b=tf.constant(5)
print(sess.run(b))
print(b)#Tensor("Const_1:0", shape=(), dtype=int32)
sess.close()
#Second Type From write a session 
#with tf.compat.v1.Session():
print('=='*20)
c1=tf.constant(10)
c2=tf.constant(11)
c3=(c1+c2)
c4 =c1 * c3 
with tf.compat.v1.Session() as sess:
    print('The Value Of Constant1 Is ==> ',sess.run(c1))
    print('The Value Of Constant2 Is ==> ',sess.run(c2))
    print('The Value Of Constant3 Is ==> ',c3.eval())
    print('The Value Of Constant4 Is ==> ',c4.eval())
sess.close()


5
Tensor("Const:0", shape=(), dtype=int32)
The Value Of Constant1 Is ==>  10
The Value Of Constant2 Is ==>  11
The Value Of Constant3 Is ==>  21
The Value Of Constant4 Is ==>  210


In [18]:
#Second Create Constant 
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
a=tf.constant(4)
b=tf.constant(4,tf.float32)
c=tf.constant([10,15,20,17,2])
d=tf.constant([[1,2,4,5],[7,8,9,10],[15,20,22,30]])
e=tf.constant('My Name Is Alhousainy & Iam a Deep Learning Engineer & I work at ISFP Company')
with tf.compat.v1.Session() as sess:
    print('The Constant A Is ==> ',sess.run(a))
    print('The Constant B Is ==> ',sess.run(b))
    print('The Constant C Is ==> ',sess.run(c))
    print('The Constant D Is ==> ',sess.run(d))
    print('The Constant E Is ==> ',sess.run(e))
sess.close()    

The Constant A Is ==>  4
The Constant B Is ==>  4.0
The Constant C Is ==>  [10 15 20 17  2]
The Constant D Is ==>  [[ 1  2  4  5]
 [ 7  8  9 10]
 [15 20 22 30]]
The Constant E Is ==>  b'My Name Is Alhousainy & Iam a Deep Learning Engineer & I work at ISFP Company'


In [6]:
#Third Type => Create A Variables 
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
c1=tf.Variable(4)
c2=tf.Variable(4,tf.float32)
c3=tf.Variable([10,15,20,17,2])
c4=tf.Variable([[1,2,4,5],[7,8,9,10],[15,20,22,30]])
c5=tf.Variable('My Name Is Alhousainy & Iam a Deep Learning Engineer & I work at ISFP Company')
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    print('The Value Of Variable C1 Is ==> ',sess.run(c1))
    print('The Value Of Variable C2 Is ==> ',sess.run(c2))
    print('The Value Of Variable C3 Is ==> ',sess.run(c3))
    print('The Value Of Variable C4 Is ==> ',sess.run(c4))
    print('The Value Of Variable C5 Is ==> ',sess.run(c5))
sess.close() 
print('***'*30)
#Change Variable by using the same variable 
S1=tf.compat.v1.keras.backend.get_session()
price=tf.Variable(40)
#var=tf.compat.v1.global_variables_initializer()
S1.run(tf.compat.v1.global_variables_initializer())
print(S1.run(price)) 
#============================================================= 
price=tf.Variable(30)
S1.run(tf.compat.v1.global_variables_initializer())
print(S1.run(price))
#=============================================================
price=tf.Variable(60)
S1.run(tf.compat.v1.global_variables_initializer())
print(S1.run(price))
#Change Value Of Variable Another Method Using Assign But Not Use The Same Name Of Variable 
value = tf.compat.v1.assign(price,150)
print('The New Value Of Variable Using Asign Is ==> ',S1.run(value))#The New Value Of Variable Using Asign Is ==>  150
value2 = tf.compat.v1.assign(price,250)
print(S1.run(value2))
print('***'*50)
print('The Last Price Is ==> ',S1.run(value2))
for j in range(7):
    price=tf.compat.v1.assign(price,price+10)
    print(j,'==> The New Price Is ==> ',S1.run(price))

The Value Of Variable C1 Is ==>  4
The Value Of Variable C2 Is ==>  4
The Value Of Variable C3 Is ==>  [10 15 20 17  2]
The Value Of Variable C4 Is ==>  [[ 1  2  4  5]
 [ 7  8  9 10]
 [15 20 22 30]]
The Value Of Variable C5 Is ==>  b'My Name Is Alhousainy & Iam a Deep Learning Engineer & I work at ISFP Company'
******************************************************************************************
40
30
60
The New Value Of Variable Using Asign Is ==>  150
250
******************************************************************************************************************************************************
The Last Price Is ==>  250
0 ==> The New Price Is ==>  260
1 ==> The New Price Is ==>  280
2 ==> The New Price Is ==>  310
3 ==> The New Price Is ==>  350
4 ==> The New Price Is ==>  400
5 ==> The New Price Is ==>  460
6 ==> The New Price Is ==>  530


In [16]:
#Fourth Type ==> Placeholder
import tensorflow as tf  
tf.compat.v1.disable_eager_execution()
S2=tf.compat.v1.keras.backend.get_session()
a=tf.compat.v1.placeholder(tf.float32)
with tf.compat.v1.Session() as S3 :
    result=S3.run(a , feed_dict={a:5})
    print('The Value Of A After Using PlaceHolder Is ==> ',result)
S2.close()
print('***'*40)
#Another Example 
S3=tf.compat.v1.keras.backend.get_session()
num1 = tf.compat.v1.placeholder(tf.float32)
num2 = num1 * 3
with tf.compat.v1.Session() as S4 :
    result1 = S4.run(num2, feed_dict={num1:5})
    print('The Final Result After num1 * num2 Is ==> ',result1)
S4.close()
print('***'*40)
#Another Example 
S5=tf.compat.v1.keras.backend.get_session()
n1=tf.compat.v1.placeholder(tf.float32)
n2=tf.compat.v1.placeholder(tf.float32)
n3=tf.compat.v1.placeholder(tf.float32)
n4=tf.compat.v1.placeholder(tf.float32)
result3 = n1 * 2 + 4 * n2 **3 + 12/n3 + n4 + 15
with tf.compat.v1.Session() as S5 :
    result4 = S5.run(result3 , feed_dict={n1:5 ,n2:12,n3:2,n4:8})
    print('The Final Result Is ==> ',result4)
S5.close()
print('***'*50)
#Another Example using constant & Placeholder
var1 = tf.compat.v1.placeholder(tf.float32)
var2 = tf.compat.v1.placeholder(tf.float32)
var3=  tf.compat.v1.placeholder(tf.float32)
var4 = tf.constant(10,tf.float32)
var5 = tf.constant(15,tf.float32)
result5 = var1 * 2 + 5 * var2 **3 + var3 *2.5 + var4 + var5
with tf.compat.v1.Session() as S6:
    result6 = S6.run(result5,feed_dict={var1:5,var2:7,var3:7.9})
    print('The Final Result Is ==> ',result6)
S6.close()

The Value Of A After Using PlaceHolder Is ==>  5.0
************************************************************************************************************************
The Final Result After num1 * num2 Is ==>  15.0
************************************************************************************************************************
The Final Result Is ==>  6951.0
******************************************************************************************************************************************************
The Final Result Is ==>  1769.75


In [24]:
import tensorflow as tf      
num1 = tf.compat.v1.placeholder(tf.float32)
result1 = num1 ** 2
with tf.compat.v1.Session() as S1 :
    result = S1.run(result1,feed_dict={num1:[2,4,5,6,10,20,30]})
    print('The Final R?esult Is ==> ',result)
S1.close()
print('**'*50)
#Another Example 
result2 = num1 ** 3
with tf.compat.v1.Session() as S2:
    result = S2.run(result2,feed_dict={num1:list(range(5,35))})
    print('The Final Result Is ==> ',result)
S2.close()
print('**'*50)

The Final R?esult Is ==>  [  4.  16.  25.  36. 100. 400. 900.]
****************************************************************************************************
The Final Result Is ==>  [  125.   216.   343.   512.   729.  1000.  1331.  1728.  2197.  2744.
  3375.  4096.  4913.  5832.  6859.  8000.  9261. 10648. 12167. 13824.
 15625. 17576. 19683. 21952. 24389. 27000. 29791. 32768. 35937. 39304.]
****************************************************************************************************


In [25]:
#Sample Example About Today Session 
import tensorflow as tf     
weights= tf.constant([5.0])
bias = tf.Variable([7.0],tf.float32)
x = tf.compat.v1.placeholder(tf.float32)
LinearRegressionModel1 = weights * x + bias 
with tf.compat.v1.Session() as s :
    s.run(tf.compat.v1.global_variables_initializer())
    print('The Final Result Is ==> ',s.run(LinearRegressionModel1,{x:[3,5,7,9]}))
s.close()
#Another Example 
print('***'*50)
#Sample Example About Today Session 
import tensorflow as tf     
weights= tf.constant([5.0])
bias = tf.Variable([7.0],tf.float32)
x = tf.compat.v1.placeholder(tf.float32)
LinearRegressionModel1 = weights * x + bias 
with tf.compat.v1.Session() as s1 :
    s1.run(tf.compat.v1.global_variables_initializer())
    print('The Final Result Is ==> ',s1.run(LinearRegressionModel1,{x:list(range(5,200))}))
s1.close()

The Final Result Is ==>  [22. 32. 42. 52.]
******************************************************************************************************************************************************
The Final Result Is ==>  [  32.   37.   42.   47.   52.   57.   62.   67.   72.   77.   82.   87.
   92.   97.  102.  107.  112.  117.  122.  127.  132.  137.  142.  147.
  152.  157.  162.  167.  172.  177.  182.  187.  192.  197.  202.  207.
  212.  217.  222.  227.  232.  237.  242.  247.  252.  257.  262.  267.
  272.  277.  282.  287.  292.  297.  302.  307.  312.  317.  322.  327.
  332.  337.  342.  347.  352.  357.  362.  367.  372.  377.  382.  387.
  392.  397.  402.  407.  412.  417.  422.  427.  432.  437.  442.  447.
  452.  457.  462.  467.  472.  477.  482.  487.  492.  497.  502.  507.
  512.  517.  522.  527.  532.  537.  542.  547.  552.  557.  562.  567.
  572.  577.  582.  587.  592.  597.  602.  607.  612.  617.  622.  627.
  632.  637.  642.  647.  652.  657.  662.  667.  6