## 1 -  Some Of Operations

In [1]:
import tensorflow as tf 
tf.compat.v1.disable_eager_execution()    
s1 =tf.constant('Hello People & My Name Is Alhousainy Abdelrahman and I a Deep Learning Engineer &')
s2 =tf.constant('Iam From Qena but I Live at Alexandria & Iam 26 Years Old & I Work At ISFP Comapny')
result =tf.compat.v1.add(s1,s2)
with tf.compat.v1.Session() as ss :
    print(ss.run(result))
print('**'*50)
#Another Examples With Used Numbers 
num1 = tf.constant(20)
num2= tf.constant(30)
with tf.compat.v1.Session() as S1:
    mult =tf.math.multiply(num1,num2)
    sub=tf.subtract(num1,num2)
    sum =tf.add(num1,num2)
    div=tf.divide(num1,num2)
    power1=tf.pow(num1,2)
    power2=tf.pow(num2,3)
    print(S1.run(mult))
    print(S1.run(sub))
    print(S1.run(sum))
    print(S1.run(div))
    print(S1.run(power1))
    print(S1.run(power2))
S1.close()
print('***'*40)
#Example 3 
L1 =tf.constant([5,7,8,9])
L2=tf.constant([10,8,11,15])
with tf.compat.v1.Session() as S2:
    func1 =tf.add(L1,num1)
    print('The Final Result Is ==> ',S2.run(func1))
    print('**'*15)
    print('The List 1 Is ==> ',S2.run(L1))
    print('The List 2 Is ==> ',S2.run(L2))
    func2=tf.add(L1,L2)
    func3=tf.multiply(L1,L2)
    func4=tf.subtract(L1,L2)
    print('L1 + L2 Is ==> ',S2.run(func2))
    print('L1 * L2 Is ==> ',S2.run(func3))
    print('L1 - L2 Is ==> ',S2.run(func4))
S2.close()

b'Hello People & My Name Is Alhousainy Abdelrahman and I a Deep Learning Engineer &Iam From Qena but I Live at Alexandria & Iam 26 Years Old & I Work At ISFP Comapny'
****************************************************************************************************
600
-10
50
0.6666666666666666
400
27000
************************************************************************************************************************
The Final Result Is ==>  [25 27 28 29]
******************************
The List 1 Is ==>  [5 7 8 9]
The List 2 Is ==>  [10  8 11 15]
L1 + L2 Is ==>  [15 15 19 24]
L1 * L2 Is ==>  [ 50  56  88 135]
L1 - L2 Is ==>  [-5 -1 -3 -6]


## 2- Matrices Operations

In [29]:
#Matrices 
import tensorflow as tf      
tf.compat.v1.disable_eager_execution()
Matrix1 = tf.constant([[5,7,8,9],[10,2,5,3],[8,9,6,5],[4,3,10,11]])
Matrix2 = tf.constant([[15,20,30,7],[4,8,9,6],[8,14,40,-12],[7,8,9,5]])
with tf.compat.v1.Session() as S3 :
    product = tf.matmul(Matrix1,Matrix2)
    print('\t\tThe Matrix 1 Is \n',S3.run(Matrix1))
    print('**'*15)
    print('\t\tThe Matrix 2 Is \n',S3.run(Matrix2))
    print('**'*15)
    print('\t\tThe Matrix 1 * Matrix 2  Is \n',S3.run(product))
    print('**'*15)
    tm1=tf.linalg.matrix_transpose(Matrix1)
    tm2=tf.linalg.matrix_transpose(Matrix2)
    print(S3.run(tm1))
    print('**'*15)
    print(S3.run(tm2))

		The Matrix 1 Is 
 [[ 5  7  8  9]
 [10  2  5  3]
 [ 8  9  6  5]
 [ 4  3 10 11]]
******************************
		The Matrix 2 Is 
 [[ 15  20  30   7]
 [  4   8   9   6]
 [  8  14  40 -12]
 [  7   8   9   5]]
******************************
		The Matrix 1 * Matrix 2  Is 
 [[230 340 614  26]
 [219 310 545  37]
 [239 356 606  63]
 [229 332 646 -19]]
******************************
[[ 5 10  8  4]
 [ 7  2  9  3]
 [ 8  5  6 10]
 [ 9  3  5 11]]
******************************
[[ 15   4   8   7]
 [ 20   8  14   8]
 [ 30   9  40   9]
 [  7   6 -12   5]]


## 3 - Graph

In [11]:
#Graph 
import tensorflow as tf
tf.compat.v1.disable_eager_execution()  
#graph =tf.Graph()
g =tf.compat.v1.get_default_graph()
g.get_operations()
num1 = tf.constant(15)
num2 = tf.constant(25)
g.get_operations() 
op1 = tf.add(num1,num2)
g.get_operations()
sess=tf.compat.v1.keras.backend.get_session()
sess.run(tf.compat.v1.global_variables_initializer())
num3 =tf.Variable(20)
num4 = tf.compat.v1.placeholder(tf.float32)
g.get_operations()
print('=='*30)
#To Know Names Of Operation In Gragh
for operation in g.get_operations():
    print(operation.name)

Const
Const_1
Const_2
Const_3
Add
Const_4
Const_5
Add_1
Variable/Initializer/initial_value
Variable
Variable/IsInitialized/VarIsInitializedOp
Variable/Assign
Variable/Read/ReadVariableOp
Const_6
Const_7
Add_2
Variable_1/Initializer/initial_value
Variable_1
Variable_1/IsInitialized/VarIsInitializedOp
Variable_1/Assign
Variable_1/Read/ReadVariableOp
Const_8
Const_9
Add_3
init
Variable_2/Initializer/initial_value
Variable_2
Variable_2/IsInitialized/VarIsInitializedOp
Variable_2/Assign
Variable_2/Read/ReadVariableOp
Const_10
Const_11
Add_4
init_1
Variable_3/Initializer/initial_value
Variable_3
Variable_3/IsInitialized/VarIsInitializedOp
Variable_3/Assign
Variable_3/Read/ReadVariableOp
Placeholder
Const_12
Const_13
Add_5
init_2
Variable_4/Initializer/initial_value
Variable_4
Variable_4/IsInitialized/VarIsInitializedOp
Variable_4/Assign
Variable_4/Read/ReadVariableOp
Placeholder_1
Const_14
Const_15
Add_6
init_3
Variable_5/Initializer/initial_value
Variable_5
Variable_5/IsInitialized/VarIsIni

In [ ]:
#Final Type Eager_Execution 
